# Hands-on 3

### CS2545 - Data Science ###
### Fall, 2021 ###
### UNB, Fredericton ###

Please complete the following and submit this notebook (filename: handson3-**lastname**-**firstname**.ipynb) to D2L by 5:00 pm, Monday, October 18. 
</br>
</br>
</br>

**Q1.**  Create a 5X5 NumPy array with random numbers. Print the element at 4th row and 4th column.

In [1]:
import numpy as np
import random

np.random.seed(987654)

# your code - start
array = np.random.rand(5,5)
print(array)
print(array[3,3])


[[0.18442322 0.43138522 0.69510932 0.16817115 0.48363266]
 [0.71496593 0.34786811 0.78536314 0.32651554 0.77108531]
 [0.76578824 0.34974314 0.21340718 0.19124298 0.66550935]
 [0.55091803 0.64246753 0.65103664 0.66186773 0.09815941]
 [0.29974641 0.94044767 0.83444694 0.80283448 0.28364443]]
0.6618677283139668


**Q2.a** The *closing_prices* list contains some historical stock prices (closing price) of a technology company listed with NYSE. The *dates* list contains the corresponding dates.  

Using list comprehension create a list *rng_prices*, which contains stock prices (closing price) that are between 125 and 135.


**Q2.b** Create a Pandas data series  *stk_ds* from the lists *closing_prices* (as values) and *dates* (as index). Then, using a NumPy function find the median stock price.

In [47]:
import numpy as np
import pandas as pd

closing_prices = [139.02, 140.85, 141.13, 145.11, 134.05, 130.55, 129.10, 130.02, 131.21, 127.20, 126.45, 124.79, 119.64, 115.40, 115.43, 116.83, 115.67, 120.06, 123.12, 124.84, 123.38, 123.54]

dates = ['10/11/2018', '10/12/2018', '10/15/2018', '10/16/2018', '10/17/2018', '10/18/2018', '10/19/2018', '10/22/2018', '10/23/2018', '10/24/2018', '10/25/2018', '10/26/2018', '10/29/2018', '10/30/2018',  '10/31/2018', '11/1/2018', '11/2/2018', '11/5/2018', '11/6/2018', '11/7/2018', '11/8/2018', '11/9/2018']

# Q2.a

rng_prices = [price for price in closing_prices if price >= 125 and price <= 135]
print(rng_prices)


# Q2.b

stk_ds = pd.Series(closing_prices, index = dates)
print(stk_ds)
median_price = np.median(stk_ds)
print(median_price)

[134.05, 130.55, 129.1, 130.02, 131.21, 127.2, 126.45]
10/11/2018    139.02
10/12/2018    140.85
10/15/2018    141.13
10/16/2018    145.11
10/17/2018    134.05
10/18/2018    130.55
10/19/2018    129.10
10/22/2018    130.02
10/23/2018    131.21
10/24/2018    127.20
10/25/2018    126.45
10/26/2018    124.79
10/29/2018    119.64
10/30/2018    115.40
10/31/2018    115.43
11/1/2018     116.83
11/2/2018     115.67
11/5/2018     120.06
11/6/2018     123.12
11/7/2018     124.84
11/8/2018     123.38
11/9/2018     123.54
dtype: float64
125.64500000000001


**Q3.**  Download the *cereal.csv* file from Hands-on 2. This includes information about the per serving nutritional content of a number of breakfast cereals. The columns in this file represent the following fields (detail and short) and data types: <br>
cereal name [name] - String <br>
manufacturer [mfr] - String <br>
type (cold/hot) [type] - String  <br>
calories (number) [calories] - Int <br>
protein(g) [protein] - Int <br>
fat(g) [fat] - Int <br>
sodium(mg) [sodium] - Int <br>
dietary fiber(g) [fiber] - Float <br>
complex carbohydrates(g) [carbo] - Float <br>
sugars(g) [sugars] -  Int <br>
display shelf (1, 2, or 3, counting from the floor) [shelf] - Int <br>
potassium(mg) [potass] - Int <br>
vitamins & minerals  [vitamins] - Int <br>
weight (in ounces) of one serving (single serving size) [weight] - Float <br>
cups per serving [cups] - Float <br>
rating - Float <br>
<br>

Note, the value -1 indicates missing data.


**Q3.a** Load the data file *cereal.csv* into a dataframe *cdf* and show the first 5 rows.


**Q3.b** Create a second dataframe  *scdf* from *cdf*, that only includes the columns *name*, *protein*,	*fat*,		*fiber*,	*carbo*,	*potass*,	*vitamins*,	and *rating*. Then show the first 5 rows of *scdf* 

**Q3.c** Using dataframe  *scdf* show the cereals with a rating more than 65.

*Hint: you can use head() function to show first 5 rows.*

In [41]:
import pandas as pd

# Q3.a 

cdf = pd.read_csv("cereal.csv", sep=";")
cdf.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [42]:
# Q3.b

scdf = cdf[["name","protein","fat","fiber","carbo","potass","vitamins","rating"]]
scdf.head()

name  protein  fat  fiber  carbo  potass  vitamins  \
0                  100% Bran        4    1   10.0    5.0     280        25   
1          100% Natural Bran        3    5    2.0    8.0     135         0   
2                   All-Bran        4    1    9.0    7.0     320        25   
3  All-Bran with Extra Fiber        4    0   14.0    8.0     330        25   
4             Almond Delight        2    2    1.0   14.0      -1        25   

      rating  
0  68.402973  
1  33.983679  
2  59.425505  
3  93.704912  
4  34.384843

In [46]:
# Q3.c

scdf[scdf.rating > 65]

name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
62             Shredded Wheat   N    C        80        2    0       0    3.0   
63     Shredded Wheat 'n'Bran   N    C        90        3    0       0    4.0   
64  Shredded Wheat spoon size   N    C        90        3    0       0    3.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0     5.0       6     280        25      3    1.00  0.33  68.402973  
3     8.0       0     330        25      3    1.00  0.50  93.704912  
62   16.0       0      95         0      1    0.83  1.00  68.235885  
63   19.0       0     140         0      1    1.00  0.67  74.472949  
64   20.0       0     120         0      1    1.00  0.67  72.801787